# Generated by Django 6.0.1 on 2026-01-22 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Практика', 'verbose_name_plural': 'Практики'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_curator',
            field=models.BooleanField(default=False, verbose_name='Является куратором'),
        ),
        migrations.AddField(
            model_name='practice',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_practices', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Прикреплённый файл'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта контакта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон контакта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название предприятия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('supervisor', 'Преподаватель-куратор'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='core.company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('ongoing', 'В процессе'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий куратора'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='report',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.practice', verbose_name='Практика'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('final', 'Итоговый')], max_length=20, verbose_name='Тип отчёта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewed_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='Проверено куратором'),
        ),
        migrations.AlterField(
            model_name='report',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь куратора'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.CharField(max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
